Update schema_validator.yaml

diff --git a/.github/workflows/schema_validator.yaml b/.github/workflows/schema_validator.yaml
--- a/.github/workflows/schema_validator.yaml
+++ b/.github/workflows/schema_validator.yaml
@@ -20,12 +20,14 @@ jobs:
       id: validation
       run: |
         yamale -s schema.yaml config/prod/neo4j2owl-config.yaml | tee validation.report
-        echo ::set-output name=report::$(cat validation.report)
+        echo ::set-output name=report::$(tail -n +3 validation.report)
     - name: Prepare schema validator comment
       if: contains(steps.validation.outputs.report, 'Error')
-      run: "echo \"<details>\n <summary> config/prod/neo4j2owl-config.yaml file failed the schema validation check </summary> \n\" > comment.md; cat validation.report >> comment.md"
+      run: |
+        "echo \"<details>\n <summary> config/prod/neo4j2owl-config.yaml file failed the schema validation check </summary> \n\" > comment.md; cat validation.report >> comment.md"
+        exit 1
     - name: Post comment validator comment
-      if: contains(steps.validation.outputs.report, 'Error')
+      if: ${{ failure() }}
       env:
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
       uses: NejcZdovc/comment-pr@v1.1.1
